### ISSUE TITLE
Allow component-generator.py to take an "archive path" parameter

### ISSUE THREAD

**Issue by koplo199** [bottlesdevs/tools#3]
It would help automation wise: the component archive is already on disk, it would spare an unnecessary re-download.

**Comment by mirkobrombin** [comment]
Good idea

**Comment by koplo199** [comment]
@mirkobrombin  Maybe by replacing the optional `rename` parameter? Because from my understanding it does not serve any purpose, as it only rename the archive name and not the final folder name

If it could be an acceptable solution for you I could submit a PR quite quickly

**Comment by mirkobrombin** [comment]
it is something left over from the old releases, I think it can be removed but better test

**Comment by koplo199** [comment]
From my testing its value has no importance (even if renaming the folder afterward like `wine-ge` is doing), but it cannot be removed from the YAML or Bottles will throw an exception

**Comment by mirkobrombin** [comment]
Need to patch Bottles to drop it entirely
